name: Lint

on:
    pull_request:
        branches:
            - dev
        paths:
            - '**'
            - '!vscode/**'
            - '!website/**'

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v3
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Cache devDependencies
              uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: os-ubuntu-latest-node18-dev-${{ hashFiles('yarn.lock') }}

            - name: Install dependencies
              run: yarn install

            - name: Lint
              run: yarn lint:check
