name: Lint

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: yarn install

            - name: Bootstrap
              run: yarn bootstrap

            - name: Lint
              run: yarn lint
