name: Test

on:
    push:
        branches:
            - main
            - dev
            - next
    pull_request:
        branches:
            - main
            - dev
            - next

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-2022]
                node: [12]
                include:
                    - node: 17
                      os: ubuntu-latest
                      experimental: true
        steps:
            - uses: actions/checkout@v2
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - uses: actions/cache@v2
              id: cache
              with:
                  path: |
                      node_modules
                      **/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Add VS 16.x
              if: matrix.os == 'windows-2022'
              uses: microsoft/setup-msbuild@v1.1
              with:
                  vs-version: '[16.0,17.0)'

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true' || matrix.os == 'windows-2022'
              run: yarn install

            - name: Bootstrap
              run: yarn bootstrap

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test:coverage
