name: Test on legacy environments

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node: [14, 16, 18, 20]
        steps:
            - uses: actions/checkout@v3
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install for build on Node.js v18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: yarn bootstrap
            - run: yarn install
            - run: yarn build

            - name: Test on Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - run: yarn install --production --ignore-engines
            - run: yarn test:coverage
