name: Test

on:
    push:
        branches:
            - master
            - next
            - dev
    pull_request:
        branches:
            - master
            - next
            - dev

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                node: [12]

        steps:
            - uses: actions/checkout@v2

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@v2
              id: cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                    ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn install

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test
